### PR TITLE
Fix JSON and next page issues

### PR DESCRIPTION
**Pull request by lukakerr**
You can use a new url to fetch JSON data:

```python
request_url = "https://www.instagram.com/" + username + "?__a=1"
```

And then access each image with:

```python
for node in data["user"]["media"]["nodes"]:
  file_url = node["display_src"]
  # Do something with file_url
```

I've also fixed the next page functionality as this changed with the new JSON, as well as removed unused libraries, and made it work with python 2.7.

Let me know any thoughts

### CODE REVIEW

**Comment by sdushantha** [comment]
I never knew that there was a new place to get the JSON data. I guess we do learn something new everyday!

#### User-Agent and JSON parser
The reason I made insta-dl with the requests module is because
1. It has the JSON parser inbuilt (one less line in the code I guess)

2. You can add a User-Agent so Instagram doesn't temporarily ban the user's IP because of the many requests.

I don't think it is possible to add User-Agent in the urllib module. We **must** add a User-Agent because when I ran the code, it stopped downloading because Instagram temporarily banned my IP.

#### Error with Python3
When running the code in Python3 I get an error on line 21 because you wrote:
```python
response = urllib.urlopen(request_url)
```
But in Python3 it has to be:
```python
response = urllib.request.urlopen(request_url)
```

In my opinion I think writing this in Python3 is better because Python3 is soon gonna be the main Python (just my opinion)

So overall, if you fix the error with Python3 and somehow add a user-agent, then I will accept you PR.

Thank you for helping!

**Comment by lukakerr** [comment]
Fixes made, keeping compatibility with python 2.7 and 3

**Comment by sdushantha** [comment]
Line 48 which is ```urllib.urlretrieve(file_url, path)``` has to be ```urllib.request.urlretrieve(file_url, path)```  in order for the code to work on Python3. Because now it is skipping all the images because an error occurs.


And also, I found out, that Instagram temporarily blocks your IP if someone goes onto the link with the JSON many times. So i recommend using a VPN when running this. 
Windscribe is a very good one. It has 10GB for free each month. (Just for your info)


Please fix line 48 and I think everything else looks great.

**Comment by sdushantha** [comment]
#### Proof Instagram Blocks You
screen shot 2017-12-29 at 12 11 01

**Comment by lukakerr** [comment]
Change made, and yeah I also use windscribe its pretty great :)

**Pull request merged**
